DROP TABLE IF EXISTS livros;

CREATE TABLE livros (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(255) NOT NULL,
    valor FLOAT NOT NULL,
    status_atual VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

